// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raftgrp.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// message
type Metadata struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_raftgrp_d69fbdcb40c2f628, []int{0}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (dst *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(dst, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type Playload struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Playload) Reset()         { *m = Playload{} }
func (m *Playload) String() string { return proto.CompactTextString(m) }
func (*Playload) ProtoMessage()    {}
func (*Playload) Descriptor() ([]byte, []int) {
	return fileDescriptor_raftgrp_d69fbdcb40c2f628, []int{1}
}
func (m *Playload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Playload.Unmarshal(m, b)
}
func (m *Playload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Playload.Marshal(b, m, deterministic)
}
func (dst *Playload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Playload.Merge(dst, src)
}
func (m *Playload) XXX_Size() int {
	return xxx_messageInfo_Playload.Size(m)
}
func (m *Playload) XXX_DiscardUnknown() {
	xxx_messageInfo_Playload.DiscardUnknown(m)
}

var xxx_messageInfo_Playload proto.InternalMessageInfo

func (m *Playload) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// FIXME: use stream to send this
type SendRequest struct {
	// Types that are valid to be assigned to Msg:
	//	*SendRequest_Meta
	//	*SendRequest_Payload
	Msg                  isSendRequest_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_raftgrp_d69fbdcb40c2f628, []int{2}
}
func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (dst *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(dst, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

type isSendRequest_Msg interface {
	isSendRequest_Msg()
}

type SendRequest_Meta struct {
	Meta *Metadata `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}
type SendRequest_Payload struct {
	Payload *Playload `protobuf:"bytes,2,opt,name=payload,proto3,oneof"`
}

func (*SendRequest_Meta) isSendRequest_Msg()    {}
func (*SendRequest_Payload) isSendRequest_Msg() {}

func (m *SendRequest) GetMsg() isSendRequest_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *SendRequest) GetMeta() *Metadata {
	if x, ok := m.GetMsg().(*SendRequest_Meta); ok {
		return x.Meta
	}
	return nil
}

func (m *SendRequest) GetPayload() *Playload {
	if x, ok := m.GetMsg().(*SendRequest_Payload); ok {
		return x.Payload
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SendRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SendRequest_OneofMarshaler, _SendRequest_OneofUnmarshaler, _SendRequest_OneofSizer, []interface{}{
		(*SendRequest_Meta)(nil),
		(*SendRequest_Payload)(nil),
	}
}

func _SendRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SendRequest)
	// msg
	switch x := m.Msg.(type) {
	case *SendRequest_Meta:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Meta); err != nil {
			return err
		}
	case *SendRequest_Payload:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Payload); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SendRequest.Msg has unexpected type %T", x)
	}
	return nil
}

func _SendRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SendRequest)
	switch tag {
	case 1: // msg.meta
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Metadata)
		err := b.DecodeMessage(msg)
		m.Msg = &SendRequest_Meta{msg}
		return true, err
	case 2: // msg.payload
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Playload)
		err := b.DecodeMessage(msg)
		m.Msg = &SendRequest_Payload{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SendRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SendRequest)
	// msg
	switch x := m.Msg.(type) {
	case *SendRequest_Meta:
		s := proto.Size(x.Meta)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SendRequest_Payload:
		s := proto.Size(x.Payload)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ACK struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACK) Reset()         { *m = ACK{} }
func (m *ACK) String() string { return proto.CompactTextString(m) }
func (*ACK) ProtoMessage()    {}
func (*ACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_raftgrp_d69fbdcb40c2f628, []int{3}
}
func (m *ACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACK.Unmarshal(m, b)
}
func (m *ACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACK.Marshal(b, m, deterministic)
}
func (dst *ACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACK.Merge(dst, src)
}
func (m *ACK) XXX_Size() int {
	return xxx_messageInfo_ACK.Size(m)
}
func (m *ACK) XXX_DiscardUnknown() {
	xxx_messageInfo_ACK.DiscardUnknown(m)
}

var xxx_messageInfo_ACK proto.InternalMessageInfo

func (m *ACK) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ACK) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type SendReply struct {
	Ack                  *ACK     `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendReply) Reset()         { *m = SendReply{} }
func (m *SendReply) String() string { return proto.CompactTextString(m) }
func (*SendReply) ProtoMessage()    {}
func (*SendReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_raftgrp_d69fbdcb40c2f628, []int{4}
}
func (m *SendReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendReply.Unmarshal(m, b)
}
func (m *SendReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendReply.Marshal(b, m, deterministic)
}
func (dst *SendReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendReply.Merge(dst, src)
}
func (m *SendReply) XXX_Size() int {
	return xxx_messageInfo_SendReply.Size(m)
}
func (m *SendReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendReply proto.InternalMessageInfo

func (m *SendReply) GetAck() *ACK {
	if m != nil {
		return m.Ack
	}
	return nil
}

func init() {
	proto.RegisterType((*Metadata)(nil), "proto.Metadata")
	proto.RegisterType((*Playload)(nil), "proto.Playload")
	proto.RegisterType((*SendRequest)(nil), "proto.SendRequest")
	proto.RegisterType((*ACK)(nil), "proto.ACK")
	proto.RegisterType((*SendReply)(nil), "proto.SendReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RaftGrouperClient is the client API for RaftGrouper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftGrouperClient interface {
	// Sends a raft message to peer
	Send(ctx context.Context, opts ...grpc.CallOption) (RaftGrouper_SendClient, error)
}

type raftGrouperClient struct {
	cc *grpc.ClientConn
}

func NewRaftGrouperClient(cc *grpc.ClientConn) RaftGrouperClient {
	return &raftGrouperClient{cc}
}

func (c *raftGrouperClient) Send(ctx context.Context, opts ...grpc.CallOption) (RaftGrouper_SendClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RaftGrouper_serviceDesc.Streams[0], "/proto.RaftGrouper/Send", opts...)
	if err != nil {
		return nil, err
	}
	x := &raftGrouperSendClient{stream}
	return x, nil
}

type RaftGrouper_SendClient interface {
	Send(*SendRequest) error
	CloseAndRecv() (*SendReply, error)
	grpc.ClientStream
}

type raftGrouperSendClient struct {
	grpc.ClientStream
}

func (x *raftGrouperSendClient) Send(m *SendRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *raftGrouperSendClient) CloseAndRecv() (*SendReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RaftGrouperServer is the server API for RaftGrouper service.
type RaftGrouperServer interface {
	// Sends a raft message to peer
	Send(RaftGrouper_SendServer) error
}

func RegisterRaftGrouperServer(s *grpc.Server, srv RaftGrouperServer) {
	s.RegisterService(&_RaftGrouper_serviceDesc, srv)
}

func _RaftGrouper_Send_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RaftGrouperServer).Send(&raftGrouperSendServer{stream})
}

type RaftGrouper_SendServer interface {
	SendAndClose(*SendReply) error
	Recv() (*SendRequest, error)
	grpc.ServerStream
}

type raftGrouperSendServer struct {
	grpc.ServerStream
}

func (x *raftGrouperSendServer) SendAndClose(m *SendReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *raftGrouperSendServer) Recv() (*SendRequest, error) {
	m := new(SendRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RaftGrouper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RaftGrouper",
	HandlerType: (*RaftGrouperServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Send",
			Handler:       _RaftGrouper_Send_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "raftgrp.proto",
}

func init() { proto.RegisterFile("raftgrp.proto", fileDescriptor_raftgrp_d69fbdcb40c2f628) }

var fileDescriptor_raftgrp_d69fbdcb40c2f628 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x77, 0xdd, 0x6d, 0xbb, 0x9d, 0x55, 0x94, 0x39, 0x48, 0x15, 0x11, 0x09, 0x14, 0x2a,
	0x42, 0xd1, 0xfa, 0x00, 0x52, 0x7b, 0xb0, 0x52, 0x04, 0x89, 0x0f, 0x20, 0x63, 0x93, 0xae, 0xc5,
	0xd4, 0xc4, 0x34, 0x3d, 0xec, 0xdb, 0x4b, 0xb2, 0x59, 0x68, 0x4f, 0x99, 0xf9, 0xf3, 0xcd, 0xfc,
	0xff, 0xc0, 0x89, 0xa5, 0x95, 0xab, 0xac, 0x19, 0x1b, 0xab, 0x9d, 0xc6, 0x4e, 0x78, 0xd8, 0x10,
	0x8a, 0x37, 0xe9, 0x48, 0x90, 0x23, 0xbc, 0x80, 0xa2, 0xb2, 0x7a, 0x67, 0x3e, 0xd7, 0x62, 0x90,
	0xde, 0xa4, 0xa3, 0x8c, 0xf7, 0x42, 0xff, 0x2a, 0xd8, 0x35, 0x14, 0xef, 0x8a, 0x6a, 0xa5, 0x49,
	0x20, 0x42, 0xee, 0xf1, 0x80, 0x1c, 0xf3, 0x50, 0xb3, 0x6f, 0x28, 0x3f, 0xe4, 0xaf, 0xe0, 0xf2,
	0x6f, 0x27, 0xb7, 0x0e, 0x87, 0x90, 0x6f, 0x64, 0x44, 0xca, 0xc9, 0x69, 0x63, 0x39, 0x6e, 0x8d,
	0xe6, 0x09, 0x0f, 0xdf, 0x78, 0x07, 0x3d, 0xd3, 0x2c, 0x1d, 0x1c, 0x1d, 0x90, 0xad, 0xd7, 0x3c,
	0xe1, 0x2d, 0xf1, 0xdc, 0x81, 0x6c, 0xb3, 0xad, 0xd8, 0x03, 0x64, 0xd3, 0xd9, 0xc2, 0x87, 0x58,
	0x6a, 0x21, 0x63, 0xce, 0x50, 0xe3, 0x39, 0x74, 0x85, 0x74, 0xb4, 0x56, 0x61, 0x5b, 0x9f, 0xc7,
	0x8e, 0xdd, 0x42, 0xbf, 0x09, 0x67, 0x54, 0x8d, 0x57, 0x90, 0xd1, 0xf2, 0x27, 0x26, 0x83, 0xe8,
	0x37, 0x9d, 0x2d, 0xb8, 0x97, 0x27, 0x4f, 0x50, 0x72, 0x5a, 0xb9, 0x17, 0x7f, 0xb6, 0xb4, 0x78,
	0x0f, 0xb9, 0x9f, 0x44, 0x8c, 0xdc, 0xde, 0x8d, 0x97, 0x67, 0x07, 0x9a, 0x51, 0x35, 0x4b, 0x46,
	0xe9, 0x57, 0x37, 0x88, 0x8f, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x89, 0x1a, 0x14, 0x73, 0x6e,
	0x01, 0x00, 0x00,
}
